/* ISpatialAudioClient binaural-path frequency-response probe.
 *
 * Measures the magnitude response (dB vs frequency) the spatial render path
 * imposes, to separate the HRTF's intrinsic coloration from the bass buildup
 * caused by summing correlated channels through independent HRTFs.
 *
 * Two routings (argv[1]):
 *   single  one Dynamic object fixed front-center (0,0,-1): ONE HRTF, the
 *           intrinsic spectral coloration of a single binaural render.
 *   bed     the full GTA-style 16-channel static bed (FL FR FC SL SR BL BR +
 *           4 Top + 4 Bottom + BackCenter, no LFE) with the SAME tone in every
 *           channel: correlated summation through 16 HRTFs.
 *
 * HRTF vs panning is chosen by the environment, not an arg: with
 * WINE_SPATIAL_PHONON pointing at libphonon the path is HRTF; without it (or a
 * bad path) the driver falls back to frequency-flat equal-power panning, which
 * is the neutral reference (a flat response modulo the endpoint).  Diff the two
 * runs of the same mode to get exactly the coloration the HRTF adds; diff bed
 * vs single (HRTF) to isolate the correlated-summation bass buildup.
 *
 * Method: a continuous sine (amp 0.25) is generated by a pump thread at a
 * frequency the main thread steps through a log-spaced grid.  Per step the main
 * thread sets the frequency, drains+discards a settle window (flushing the old
 * tone through the loopback latency), then loopback-captures a measurement
 * window and reports the Goertzel power (L+R) at the tone frequency.  The
 * endpoint's own response is identical across modes/configs, so it cancels in
 * the diffs; only the relative shape matters.
 *
 * Prints one "freq=<hz> level_db=<x>" line per step (plus a header), so the
 * absolute scale is arbitrary; normalize each curve at 1 kHz when comparing.
 * Requires spatial sound enabled (WINE_SPATIAL_SOUND=1); prints spatial=off and
 * exits 77 otherwise.  Args: [mode=bed] [settle_ms=200] [window_ms=300]
 *   [fmin fmax nsteps]: optional dense log-spaced grid (1 kHz auto-anchored).
 */
#define COBJMACROS
#define INITGUID
#include <windows.h>
#include <initguid.h>
#include <mmdeviceapi.h>
#include <audioclient.h>
#include <spatialaudioclient.h>
#include <devpkey.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int _fltused = 0x9875;

static volatile LONG stop;
static volatile LONG perrs;
static volatile double g_freq = 1000.0;   /* current tone frequency, set by main */
static int g_bed;                         /* 1 = bed mode, 0 = single */
static ISpatialAudioClient *g_sac;

/* GTA's 0x3ffee static bed: 7.1.4 + bottom quad + back-center, no LFE */
static const AudioObjectType bed_types[] = {
    AudioObjectType_FrontLeft, AudioObjectType_FrontRight, AudioObjectType_FrontCenter,
    AudioObjectType_SideLeft, AudioObjectType_SideRight,
    AudioObjectType_BackLeft, AudioObjectType_BackRight,
    AudioObjectType_TopFrontLeft, AudioObjectType_TopFrontRight,
    AudioObjectType_TopBackLeft, AudioObjectType_TopBackRight,
    AudioObjectType_BottomFrontLeft, AudioObjectType_BottomFrontRight,
    AudioObjectType_BottomBackLeft, AudioObjectType_BottomBackRight,
    AudioObjectType_BackCenter,
};
#define NBED (int)(sizeof(bed_types)/sizeof(bed_types[0]))

static const char *hrs(HRESULT hr){ static char b[32]; sprintf(b,"0x%08lx",(unsigned long)hr); return b; }

static DWORD WINAPI pump_main(void *arg)
{
    ISpatialAudioObjectRenderStream *sas = NULL;
    ISpatialAudioObject *sao[16] = {0};
    int nobj = g_bed ? NBED : 1;
    SpatialAudioObjectRenderStreamActivationParams params;
    PROPVARIANT prop;
    IAudioFormatEnumerator *afe = NULL;
    WAVEFORMATEX *fmt = NULL;
    HANDLE evt;
    HRESULT hr;
    double phase = 0;
    int i;

    (void)arg;
    CoInitializeEx(NULL, COINIT_MULTITHREADED);

    hr = ISpatialAudioClient_GetSupportedAudioObjectFormatEnumerator(g_sac, &afe);
    if (FAILED(hr)) { printf("GetFormatEnumerator %s\n", hrs(hr)); InterlockedIncrement(&perrs); return 1; }
    hr = IAudioFormatEnumerator_GetFormat(afe, 0, &fmt);
    if (FAILED(hr)) { printf("GetFormat %s\n", hrs(hr)); InterlockedIncrement(&perrs); return 1; }

    evt = CreateEventW(NULL, FALSE, FALSE, NULL);

    memset(&params, 0, sizeof(params));
    params.ObjectFormat = fmt;
    if (g_bed)
        for (i = 0; i < NBED; i++) params.StaticObjectTypeMask |= bed_types[i];
    params.MinDynamicObjectCount = g_bed ? 0 : 1;
    params.MaxDynamicObjectCount = g_bed ? 0 : 4;
    params.Category = AudioCategory_GameEffects;
    params.EventHandle = evt;
    params.NotifyObject = NULL;

    PropVariantInit(&prop);
    prop.vt = VT_BLOB;
    prop.blob.cbSize = sizeof(params);
    prop.blob.pBlobData = (BYTE *)&params;

    hr = ISpatialAudioClient_ActivateSpatialAudioStream(g_sac, &prop,
            &IID_ISpatialAudioObjectRenderStream, (void **)&sas);
    if (FAILED(hr)) { printf("ActivateStream %s\n", hrs(hr)); InterlockedIncrement(&perrs); return 1; }

    if (g_bed) {
        for (i = 0; i < NBED; i++) {
            hr = ISpatialAudioObjectRenderStream_ActivateSpatialAudioObject(sas, bed_types[i], &sao[i]);
            if (FAILED(hr)) { printf("ActivateObject bed[%d] %s\n", i, hrs(hr)); InterlockedIncrement(&perrs); return 1; }
        }
    } else {
        hr = ISpatialAudioObjectRenderStream_ActivateSpatialAudioObject(sas, AudioObjectType_Dynamic, &sao[0]);
        if (FAILED(hr)) { printf("ActivateObject dyn %s\n", hrs(hr)); InterlockedIncrement(&perrs); return 1; }
    }

    hr = ISpatialAudioObjectRenderStream_Start(sas);
    if (FAILED(hr)) { printf("Start %s\n", hrs(hr)); InterlockedIncrement(&perrs); return 1; }

    while (!stop)
    {
        UINT32 dyn, frames, f, len;
        double w;

        if (WaitForSingleObject(evt, 1000) != WAIT_OBJECT_0) { InterlockedIncrement(&perrs); continue; }

        hr = ISpatialAudioObjectRenderStream_BeginUpdatingAudioObjects(sas, &dyn, &frames);
        if (FAILED(hr)) { InterlockedIncrement(&perrs); continue; }

        if (!g_bed)
            ISpatialAudioObject_SetPosition(sao[0], 0.0f, 0.0f, -1.0f);

        w = 2.0 * 3.14159265358979 * g_freq / fmt->nSamplesPerSec;
        for (f = 0; f < frames; f++)
        {
            float s = (float)(0.25 * sin(phase));
            phase += w;
            if (phase > 6.283185307179586) phase -= 6.283185307179586;
            for (i = 0; i < nobj; i++) {
                BYTE *buf = NULL;
                if (sao[i] && SUCCEEDED(ISpatialAudioObject_GetBuffer(sao[i], &buf, &len)) && buf)
                    ((float *)buf)[f] = s;
            }
        }
        /* GetBuffer must be called on every object each cycle or it invalidates;
         * the loop above already fetched each one, so just end the update */
        hr = ISpatialAudioObjectRenderStream_EndUpdatingAudioObjects(sas);
        if (FAILED(hr)) InterlockedIncrement(&perrs);
    }

    ISpatialAudioObjectRenderStream_Stop(sas);
    for (i = 0; i < nobj; i++) if (sao[i]) ISpatialAudioObject_Release(sao[i]);
    ISpatialAudioObjectRenderStream_Release(sas);
    IAudioFormatEnumerator_Release(afe);
    CloseHandle(evt);
    return 0;
}

/* Goertzel power at g_freq over buf[0..n) */
static double goertzel(const float *buf, int n, double freq, double rate)
{
    double coeff = 2.0 * cos(2.0 * 3.14159265358979 * freq / rate);
    double s0, s1 = 0, s2 = 0;
    int k;
    if (n <= 0) return 0;
    for (k = 0; k < n; k++) { s0 = buf[k] + coeff * s1 - s2; s2 = s1; s1 = s0; }
    return 2.0 * (s1 * s1 + s2 * s2 - coeff * s1 * s2) / ((double)n * n);
}

static IAudioCaptureClient *g_cc;
static int g_ch, g_isFloat;

/* drain loopback packets; if cap!=NULL accumulate into capL/capR up to cap frames, else discard */
static int drain(float *capL, float *capR, int cap, int count)
{
    UINT32 pkt;
    while (SUCCEEDED(IAudioCaptureClient_GetNextPacketSize(g_cc, &pkt)) && pkt)
    {
        BYTE *data; UINT32 frames, f; DWORD flags;
        if (FAILED(IAudioCaptureClient_GetBuffer(g_cc, &data, &frames, &flags, NULL, NULL))) break;
        for (f = 0; f < frames; f++)
        {
            if (capL && count < cap)
            {
                if (g_isFloat) { capL[count] = ((float *)data)[f*g_ch]; capR[count] = ((float *)data)[f*g_ch+1]; }
                else { capL[count] = ((short *)data)[f*g_ch]/32768.0f; capR[count] = ((short *)data)[f*g_ch+1]/32768.0f; }
                count++;
            }
        }
        IAudioCaptureClient_ReleaseBuffer(g_cc, frames);
    }
    return count;
}

/* Optional render-endpoint selection by friendly-name substring (env WPW_SINK),
 * so the probe can target a null sink without touching the system default. */
static IMMDevice *pick_device(IMMDeviceEnumerator *en, const char *want)
{
    IMMDeviceCollection *col = NULL;
    IMMDevice *d = NULL, *found = NULL;
    UINT n = 0, i;
    if (FAILED(IMMDeviceEnumerator_EnumAudioEndpoints(en, eRender, DEVICE_STATE_ACTIVE, &col)))
        return NULL;
    IMMDeviceCollection_GetCount(col, &n);
    for (i = 0; i < n; i++) {
        IPropertyStore *ps = NULL;
        PROPVARIANT pv;
        char name[256] = "";
        if (FAILED(IMMDeviceCollection_Item(col, i, &d))) continue;
        if (SUCCEEDED(IMMDevice_OpenPropertyStore(d, STGM_READ, &ps))) {
            PropVariantInit(&pv);
            if (SUCCEEDED(IPropertyStore_GetValue(ps, (const PROPERTYKEY *)&DEVPKEY_Device_FriendlyName, &pv)) && pv.vt == VT_LPWSTR)
                WideCharToMultiByte(CP_UTF8, 0, pv.pwszVal, -1, name, sizeof(name), NULL, NULL);
            PropVariantClear(&pv);
            IPropertyStore_Release(ps);
        }
        printf("  endpoint[%u]: %s\n", i, name);
        if (!found && want && strstr(name, want)) { found = d; continue; }
        IMMDevice_Release(d);
    }
    IMMDeviceCollection_Release(col);
    return found;
}

int main(int argc, char **argv)
{
    double freqs[300];
    int nfreq = 0;
    HRESULT hr;
    UINT32 rate, maxdyn = 0;
    int settle_ms, window_ms, k, cap;
    IMMDeviceEnumerator *en = NULL;
    IMMDevice *dev = NULL;
    IAudioClient *ac = NULL;
    WAVEFORMATEX *wfx = NULL;
    float *capL, *capR;
    HANDLE pt;

    g_bed = (argc > 1 && !strcmp(argv[1], "single")) ? 0 : 1;
    settle_ms = argc > 2 ? atoi(argv[2]) : 200;
    window_ms = argc > 3 ? atoi(argv[3]) : 300;

    if (argc > 6) {
        double fmin = atof(argv[4]), fmax = atof(argv[5]);
        int ns = atoi(argv[6]), j, has1k = 0;
        if (fmin < 1.0) fmin = 1.0;
        if (fmax <= fmin) fmax = fmin * 2.0;
        if (ns < 2) ns = 2;
        if (ns > 256) ns = 256;
        for (j = 0; j < ns; j++) {
            double fv = fmin * pow(fmax / fmin, (double)j / (ns - 1));
            freqs[nfreq++] = fv;
            if (fv > 985.0 && fv < 1015.0) has1k = 1;
        }
        if (!has1k && nfreq < 299) freqs[nfreq++] = 1000.0;
        for (j = 1; j < nfreq; j++) {   /* insertion sort ascending */
            double key = freqs[j]; int m = j - 1;
            while (m >= 0 && freqs[m] > key) { freqs[m + 1] = freqs[m]; m--; }
            freqs[m + 1] = key;
        }
    } else {
        static const double dfl[] = {
            40, 55, 75, 100, 140, 190, 260, 360, 500, 700, 1000,
            1400, 2000, 2800, 4000, 5600, 8000, 11000, 15000 };
        for (nfreq = 0; nfreq < (int)(sizeof(dfl) / sizeof(dfl[0])); nfreq++)
            freqs[nfreq] = dfl[nfreq];
    }

    CoInitializeEx(NULL, COINIT_MULTITHREADED);
    hr = CoCreateInstance(&CLSID_MMDeviceEnumerator, NULL, CLSCTX_ALL, &IID_IMMDeviceEnumerator, (void **)&en);
    if (FAILED(hr)) { printf("CoCreate %s\n", hrs(hr)); return 1; }
    {
        const char *want = getenv("WPW_SINK");
        if (want && want[0]) {
            dev = pick_device(en, want);
            if (!dev) { printf("sink '%s' not found\n", want); return 1; }
        } else {
            hr = IMMDeviceEnumerator_GetDefaultAudioEndpoint(en, eRender, eConsole, &dev);
            if (FAILED(hr)) { printf("GetDefault %s\n", hrs(hr)); return 1; }
        }
    }

    hr = IMMDevice_Activate(dev, &IID_ISpatialAudioClient, CLSCTX_ALL, NULL, (void **)&g_sac);
    if (FAILED(hr)) { printf("ISpatialAudioClient %s\n", hrs(hr)); return 1; }
    hr = ISpatialAudioClient_GetMaxDynamicObjectCount(g_sac, &maxdyn);
    if (FAILED(hr)) { printf("GetMaxDynamicObjectCount %s\n", hrs(hr)); return 1; }
    if (!maxdyn) { printf("spatial=off\n"); return 77; }

    hr = IMMDevice_Activate(dev, &IID_IAudioClient, CLSCTX_ALL, NULL, (void **)&ac);
    if (FAILED(hr)) { printf("Activate %s\n", hrs(hr)); return 1; }
    hr = IAudioClient_GetMixFormat(ac, &wfx);
    if (FAILED(hr)) { printf("GetMixFormat %s\n", hrs(hr)); return 1; }
    g_ch = wfx->nChannels;
    rate = wfx->nSamplesPerSec;
    g_isFloat = (wfx->wBitsPerSample == 32);
    if (g_ch < 2) { printf("mono endpoint\n"); return 77; }
    hr = IAudioClient_Initialize(ac, AUDCLNT_SHAREMODE_SHARED, AUDCLNT_STREAMFLAGS_LOOPBACK, 5000000, 0, wfx, NULL);
    if (FAILED(hr)) { printf("Initialize %s\n", hrs(hr)); return 1; }
    hr = IAudioClient_GetService(ac, &IID_IAudioCaptureClient, (void **)&g_cc);
    if (FAILED(hr)) { printf("GetService %s\n", hrs(hr)); return 1; }

    cap = (window_ms + 50) * (int)rate / 1000;
    capL = malloc(sizeof(float) * cap);
    capR = malloc(sizeof(float) * cap);
    if (!capL || !capR) { printf("malloc failed\n"); return 1; }

    printf("mode=%s rate=%u ch=%d max_dynamic_objects=%u settle_ms=%d window_ms=%d\n",
           g_bed ? "bed" : "single", rate, g_ch, maxdyn, settle_ms, window_ms);

    IAudioClient_Start(ac);
    pt = CreateThread(NULL, 0, pump_main, NULL, 0, NULL);

    for (k = 0; k < nfreq; k++)
    {
        DWORD t0;
        int count;
        double pl, pr, p, db;

        g_freq = freqs[k];

        t0 = GetTickCount();                       /* settle: flush old tone */
        while ((int)(GetTickCount() - t0) < settle_ms) { Sleep(5); drain(NULL, 0, 0, 0); }

        count = 0; t0 = GetTickCount();            /* measure */
        while ((int)(GetTickCount() - t0) < window_ms) { Sleep(5); count = drain(capL, capR, cap, count); }

        pl = goertzel(capL, count, freqs[k], rate);
        pr = goertzel(capR, count, freqs[k], rate);
        p = pl + pr;
        db = p > 1e-20 ? 10.0 * log10(p) : -200.0;
        printf("freq=%.1f level_db=%.2f\n", freqs[k], db);
        fflush(stdout);
    }

    stop = 1;
    WaitForSingleObject(pt, 3000);
    IAudioClient_Stop(ac);
    if ((int)perrs) printf("pump_errors=%d\n", (int)perrs);
    return 0;
}
